version: '3.8'

services:
  # Aplicação Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eco-diapers-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://db:5432/ecodiapersdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    networks:
      - eco-diapers-network

  # Banco de dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: eco-diapers-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ecodiapersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eco-diapers-network

  # PgAdmin para gerenciamento do banco (opcional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: eco-diapers-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    networks:
      - eco-diapers-network

volumes:
  postgres-data:
    driver: local

networks:
  eco-diapers-network:
    driver: bridge